config/routes.rb
Rails.application.routes.draw do
  #root 'static_owners#home'
  #get '/about', to: 'static_owners#about'
  root 'owners#index'

  resources :owners

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :owner

  validates :owner_name, length: {2..50}
  validates :age, numericality: { only_integer: true,
    greater_than_or_equal_to: 18}, allow_blank: true, on: update
  validates :dog_name, presence: true on: create
  validates :city, allow_blank: true
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :dogs

  def self.order_owner_name #class method
    order(:owner_name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  before_action :choose_owner, only: [:show, :update, :edit, :destroy]

  def index
    @owner = Owner.all
  end

  def show
  end

  def new
    @owner = Owner.new
    render partial: 'owners/form'
  end

  def edit
    render partial: 'owners/form'
  end

  def create
    @owner = Owner.new(owner_params)
      if @owner.save
        redirect_to owners_path
      else
        render :new
      end
    end

  def update
    if @owner.update(owner_params)
      redirect_to @owner
    else
      render :edit
    end
  end

  def destroy
    @owner.destroy
    redirect_to owners_path
  end

private
  def choose_owner
    @owner = Owner.find(params[:id])
  end

  def owner_params
    params.require(:owner).permit(:owner_name, :age, :dog_name, :city)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Owners', owners_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/owners/_form.html.erb
<h1><%= @owner.id ? 'Edit an Owner' : 'Create a new Owner' %></h1>

<%= form_for @owner do |f| %>
  <%= f.label :owner_name %>
  <%= f.text_field :owner_name, required: true, autofocus: true %>

  <%= f.label :dog_name %>
  <%= f.text_field :dog_name, required: true %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.submit %>
<% end %>

app/views/owners/edit.html.erb
<h1>Owners#edit</h1>
<p>Find me in app/views/owners/edit.html.erb</p>

app/views/owners/index.html.erb
<h1>All Owners  </h1>

<ul>
  <% @owners.each do |owner| %>
  <li><%= link_to owner.name, owner_path(owner) %></li>
  <li><%= link_to 'Edit Owner', edit_owner_path(owner) %></li>
  <li><%= link_to 'Destroy Owner', owner, method: :delete %></li>
  <% end %>
</ul>

<%= link_to 'Create New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>Owners#new</h1>

app/views/owners/show.html.erb
<h1>Owners#show</ h1>
<%= @owner.owner_name %>
<%= @owner.age %>
<%= @owner.dog_name %>
<%= @owner.city %>

<hr />
<p>What do you want to do?</p>
<%= link_to 'Edit Owner', edit_owner_path(@owner) %>
<%= link_to 'Delete Owner', @owner, method: :delete %>

<%= link_to 'Back', owners_path %>